# Generated by Django 4.1.3 on 2022-11-27 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exchange", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="password",
            new_name="passWord",
        ),
    ]
